### ISSUE TITLE
Parallel processing as a reason to install the developer version?

### ISSUE THREAD

**Issue by ConjuringCoffee** [abapGit/docs.abapgit.org#134]
`install.md` states that the developer version is targeted at developers contributing to the codebase. However, isn't it true that the developer version supports parallel processing, while the standalone version does not? 

I find the performance gains of the parallel processing to be a good reason to install the developer version even if you don't intend to contribute. I therefore believe this information should be added to `install.md`. What do you think?

**Comment by larshp** [comment]
yea, good point IMHO, feel free to open a pull request
