### ISSUE TITLE
Fix all broken links after redesign

### ISSUE THREAD

**Issue by larshp** [abapGit/docs.abapgit.org#138]
seems like all existing links to documentation are broken after redesign?

https://github.com/microsoft/aisdkforsapabap/issues/14

add the old corresponding files and have those redirect to the new urls

**Comment by mbtools** [comment]
https://github.com/vuepress/vuepress-plugin-html-redirect looks promising

**Comment by gopalnair** [comment]
Fixed the links in AI SDK documentation site.
Closed Issue : https://github.com/microsoft/aisdkforsapabap/issues/14

**Comment by larshp** [comment]
https://github.com/SAP/styleguides/pull/328

**Comment by kjetil-kilhavn** [comment]
https://github.com/SAP/styleguides/pull/329 too ...
