### ISSUE TITLE
add CHKO, CHKC and CHKV

### ISSUE THREAD

**Issue by albertmink** [abapGit/docs.abapgit.org#14]

**Comment by albertmink** [comment]
can't assign the issue to me, so this one goes to ME

**Comment by albertmink** [comment]
see PR on AbapGit [here ](https://github.com/abapGit/abapGit/pull/5163)

**Comment by larshp** [comment]
you should have more access now

but anyhow, this is a very small change, so feel free to just open the PR without an issue
