### ISSUE TITLE
Inconsistent logo use?

### ISSUE THREAD

**Issue by ConjuringCoffee** [abapGit/docs.abapgit.org#142]
Is it on purpose that two different images are used for the abapGit logo?

In the application and in the documentation:
![image](https://github.com/abapGit/docs.abapgit.org/assets/72548231/04ce83a7-9e3a-497a-b5ec-27e695e9894a)

In GitHub and favicon of the documentation:
![image](https://github.com/abapGit/docs.abapgit.org/assets/72548231/cb830fe9-f1c9-4163-819d-d9c42b29e850)
![image](https://github.com/abapGit/docs.abapgit.org/assets/72548231/7babb673-5509-4b11-bdda-7a2eb521b53e)

**Comment by mbtools** [comment]
That's the current state https://docs.abapgit.org/user-guide/other/logos.html 

Feel free to suggest a better favicon that combines the git logo with "abapGit"

**Comment by ConjuringCoffee** [comment]
My question was answered: This was a conscious decision. Thanks :) 

I don't have a better suggestion at the moment, so I'm closing this issue.
