### ISSUE TITLE
abapGit vs gCTS

### ISSUE THREAD

**Issue by mbtools** [abapGit/docs.abapgit.org#23]
We should add a comparison of abapGit and gCTS to the documentation. As a start a simple table with topics will do. We can add more detailed descriptions later.

Let's use this issue to collect topics (including items that are the same for both)...

Topic | abapGit | gCTS
------|----------|--------
Availability for SAP releases | 702 and higher | 754 and higher (AS ABAP 1909)
Upgrade | at will | SAP release upgrade
Conceptual focus | objects (git content) | commits (git history) 
Scope of repositories | based on SAP packages | based on collection of transports
Support for local developments ($ packages) | yes | no
Support for transportable developments (y/z packages, /namespace/) | yes | yes
Supported object types | some | all
Support for customizing | yes (via Business Configuration Sets) | yes (via CDAT, TDAT, VDAT)
Support for table content | yes (beta) | TABU ?
Support for AFF | 4 object types | 0
"Single source of truth" | in git | is it git or SAP ?
Local repository | in ABAP memory | on ABAP file server 
Remote repository | many git servers | GitHub, Gitlab, other with restrictions
Git folder structure | `/<package>/<subpackage>/files` (per R3TR object) | `/objects/<object_type>/<object>/files` (per LIMU object)
Git file formats (metadata) | `.xml` and some `.json` (AFF) | `.json` only
Git file formats (ABAP code) | `.abap` | `.abap`
Git file split (ABAP classes) | one file per class | one file per method
Git end-of-file | empty line | no empty line (contrary to AFF)
Push (stage/commit) | by object | by transport
Push (patch/commit) | by object | no 
Pull (latest commit) | yes | yes
Pull (any commit) | yes | yes
Pull (from PR) | yes | ?
Pull (from fork) | yes | no
Background mode | yes | no
Switch branches | yes |
Switch tags | yes |
Merge conflict resolution | in git, doesn't happen in abapGit by design | in ABAP or git
Show diffs | yes | no (only object name)|
Jump to object maintenance | yes | no
Activity log | no | yes
Define prerequisites | yes | yes
Define dependencies | yes (apack) | yes
Usage in open source | 220+ | 0
Bugs and feature requests/development | fully open | fully closed (behind login)
Integration with transport tools | yes | yes
Integration in development tools | yes | yes
Use for deployment (dev>qa>prod) | possible, but not recommended | yes
Use for delivery (to customers/other landscapes) | yes | no

**Comment by sbcgua** [comment]
- Use for deployment - yes :) I do deploy with ag :) Though we should improve it ...
- granularity of commits: AG - free (thus development flow based), gCTS - transport only
- user exits: ag yes, gCTS ... probably also yes but the scope is unknown
- class source: in one file versus method per file (inconvenient)

**Comment by mbtools** [comment]
"deploy" can mean a) to a development system in another landscape or b) to another system in the same landscape. AG does both but we recommend only a) and use CTS for b). b) with AG works under certain conditions which we should document as well.

**Comment by sbcgua** [comment]
Ah ... hmmm ... but then I'd suggest changing the term. I mean deployment between dev systems of different landscapes (to my clients). And this works (with certain limitation). 
Deployment DEV -> QA -> PROD - this should be done by CTS in my opinion. 

Maybe write just you suggested ? "Deployment between landscapes" and "Deployment inside same landscape (DEV->QA_PRD)" ?

**Comment by flaiker** [comment]
I think that might be software deployment versus software delivery regarding the terms?

**Comment by rahulfaze** [comment]
You are just comparing two things so People are eager to understand what exactly you want to understand or share with them. Please let us know in details Thanks

**Comment by ConjuringCoffee** [comment]
> @ConjuringCoffee where did you get the information regarding object types? This is from the official slides from the Open SAP course from 2021

This comes from personal experience with the system (release 7.55). I haven't tested it in a later release yet because we blocked committing BC Sets using custom logic. My memory is a little fuzzy on the details here to be honest, but here's how I remember it: The BC Set was committed as an object to the repository. When switching the system to the commit containing the BC Set, the changes were correctly deployed. Steps after that were problematic: I think switching back to a previous commit didn't roll back the changes properly, and handling the table entries as e.g. TABUs wasn't possible in parallel without side-effects, I think.

So maybe you could say that yes, the object type is supported, but it can't be handled properly in a realistic development scenario.

**Comment by larshp** [comment]
closing
