### ISSUE TITLE
docs: update SAP Note Links to me.sap.com

### ISSUE THREAD

**Issue by schmelto** [abapGit/docs.abapgit.org#40]
As the Support Launchpad will be transitioned to SAP for Me should the SAP Note Links in the documentation be updated as well?

For example:
```diff
-https://launchpad.support.sap.com/#/notes/1240796
+https://me.sap.com/notes/1240796
```
(see [here](https://github.com/abapGit/docs.abapgit.org/blame/main/docs/guide-authentication.md#L11))

**Comment by mbtools** [comment]
It's not necessary since the old links remain valid (I assume indefinitely since they are everywhere).

For new docs we should certainly use the new links.
